- name: npm cfg
  copy:
    src: dot.npmrc
    dest: "{{ home }}/.npmrc"

- name: yarn cfg
  copy:
    src: dot.yarnrc
    dest: "{{ home }}/.yarnrc"

- name: yarn v2 cfg
  copy:
    src: dot.yarnrc.yml
    dest: "{{ home }}/.yarnrc.yml"

- name: pkgs
  package:
    name:
      - nodejs
      - node-gyp
      - yarn
    state: present
  become: yes
